/**
 * Project Euler Problem #002
 * By: Jason Moyer
 *
 * Problem: "Even Fibonacci numbers"
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *  By starting with 1 and 2, the first 10 terms will be:
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *  find the sum of the even-valued terms.
 */
public final class pe002 {
    public static void main (String[] args)
    {
        int fib1 = 1;
        int fib2 =2;
        int fibonacci = 0;
        int sum = 0;

        for (int counter = 3; counter <= 33; counter++)
        {
            fibonacci = fib1 + fib2;
            fib1 = fib2;
            fib2 = fibonacci;
            if (fibonacci % 2 == 0)
            {
                sum = sum + fibonacci;
            }
            else
            {
                continue;
            }
        }
        System.out.println(sum + 2);
    }
}
